### ISSUE TITLE
Vent roof control

### ISSUE THREAD

**Issue by Kemmey** [Kemmey/Kemmey-TeslaWatch-Public#42]

**Comment by Kemmey** [comment]
Add vent roof control for model s vehicles with that option 

Also hide vent windows control for vehicles without that possibility

**Comment by Kemmey** [comment]
Please test this out in build 168 :-D

**Comment by nachtbraker** [comment]
Will do, thanks for adding this!

**Comment by Kemmey** [comment]
Btw, it was broken in 168 - fixed in 171 - I hope 🤞 :-D

**Comment by nachtbraker** [comment]
Thanks! I will test it in the morning. Just got 171 installed.

I just noticed that the Vent Windows button is also still available. I'll try again if it does anything, but a few days ago it didn't.

And totally unrelated 😁 (plus I hardly ever use it): in the iPhone app there is also a Homelink button. I could not find it in the watch app.

**Comment by Kemmey** [comment]
I couldn't find a way to test if window control is available or not. Unless it applies to all model s vehicles?

Homelink require FSD - for som weird reason...

**Comment by nachtbraker** [comment]
@Kemmey Vent roof on the watch does not work. The watch gives a short vibration, but nothing happens on the car. Next I opened the roof from the phone app, then pressed the button on the watch again to see if it would close, but that didn't work either.

Homelink: I don't have FSD, but I do have Homelink indeed. I'll have to drive to a different location where I have a working Homelink garage door. I'll see if I can go there one of these days.

**Comment by Kemmey** [comment]
@nachtbraker I made a mistake with the sunroof - I've already fixed it, but haven't shipped the build yet. I think it'll work :-D

I've added HomeLink debug output - basically it'll report if the vehicle sees a nearby homelink device that can be actuated - that is the trigger to show the button.

**Comment by nachtbraker** [comment]
@Kemmey Thanks! Which build should I test this? I see 174 ready to install now.

**Comment by Kemmey** [comment]
@nachtbraker build 177 that just went out. There's also a debug output that will show if Homelink is nearby

**Comment by wombat996** [comment]
Homelink worked great. Nice to have options!

**Comment by nachtbraker** [comment]
@Kemmey I tested Vent Roof on build 177 and it works, many thanks (again)!

Vent windows still does nothing, and as it is not on the iPhone app either, I think it is safe to assume it just isn't available on my configuration. Maybe it is only available on the Model S without the pano roof?
